version: "2"
services:
  rest:
    image: blkio10/explorer-free:1.0.0
    container_name: blk-explorer-free
    ports:
        - 8081:8081
    environment:
        - JAVA_OPTS=
        - EXPLORER_PORT=8081
        - NODE_ENDPOINT=http://172.13.0.2:8545
        - MONGO_CLIENT_URI=mongodb://mongodb:27017
        - MONGO_DB_NAME=blk-quorum-dev
        - UI_IP=http://web:5000
    depends_on:
        - mongodb
    networks:
        - ovl_net

  web:
    image: blkio10/explorer-ui-free:1.0.0
    container_name: blk-explorer-ui-free
    ports:
        - 5000:5000
    environment:
        - REACT_APP_EXPLORER=http://13.125.170.24:8081
    networks:
        - ovl_net

  mongodb:
    image: mongo:3.4.10
    container_name: blk-mongodb-free
    ports:
        - 28017:27017
    entrypoint: mongod --smallfiles --logpath=/dev/null --bind_ip "0.0.0.0"
    networks:
        - ovl_net



networks:
  ovl_net:
    external:
       name: nnodes_quorum_net
